oakleywindiate/whats-cookin

src/classes/RecipeRepository.js, src/scripts.js, test/RecipeRepository-test.js
- Create `RecipeRepository.js`
- Create `RecipeRepository-test.js`
- `RecipeRepository.js`
- Implementing MVP for RecipeRepository and RecipeRepository-test
- N/A
- N/A
- N/A
- N/A
Close Issues:
Close #1
Close #4
=> Feature/recipe repository/ow

src/classes/RecipeRepository.js, src/scripts.js, test/RecipeRepository-test.js
- Test functionality of methods 
- N/A
- N/A
- Filter tag method
- N/A
-
-
Close Issues:
#14
=> Features/user stories/nb

dist/index.html
- Creates `index.html` skeleton for project
- `index.html`
- Creation of html set-up
- N/A
- N/A
- N/A
- N/A
Close Issues:
Close #15
=> Create index.html skeleton

dist/index.html, src/classes/RecipeRepository.js, src/scripts.js, test/RecipeRepository-test.js
- Create functions for `findRecipeId` and `createRecipeList`
- `scripts.js`
- 1) function for creating a list of recipies
- 2) function for finding recipe Id and returning the recipe object
- N/A
- N/A
- N/A
- N/A
Close Issues:
Close #6
=> Feature/user stories v2/ow

dist/index.html, src/scripts.js
- Creates starting functionality for searching tags and names 
- scripts.js 
- searchability for tags and names
- 
-
-
-
Close Issues:
=> Feature/filter search recipes/rh

dist/index.html, src/scripts.js
- Displays searched recipes on the application
- scripts.js
- Ability to display searched recipes and click to get more information about a searched recipe
- N/A
- We'll fix resetting searched recipes later
- N/A
- N/A
Close #8 
Close #9
=> Update functionality to display searched recipes on the DOM

src/classes/RecipeRepository.js, src/classes/User.js, src/classes/UserRepository.js, test/RecipeRepository-test.js, test/User-test.js, test/UserRepository-test.js
- Creates User and UserRepository classes
- UserRepository.js
-functionality to favorite and unfavorite recipes
- moved method to find recipe by ID out of scripts and into RecipeRepository class
- N/A
-N/A
-N/A
Close Issues:
Close #28
=> Features/user favorite recipes/nb

src/classes/User.js, test/User-test.js
- Create methods for finding tags and names in favorites in `User.js`
- Create tests for `User.js` methods
- `User-test.js`
- Method for finding name
- Method for finding tag
- N/A
- N/A
- N/A
- N/A
Close Issues:
Close #30
=> Create test and method for filtering name and tags

dist/index.html, src/classes/User.js, src/scripts.js, src/styles.css, test/User-test.js, test/UserRepository-test.js
- Creates functionality for modal view when clicking a recipe as well as favoriting a recipe
- Scripts.js
- Modal and favoriting recipes
- Refactored the UserRepository test
-
-
-
Close Issues:
Close #33 
Close #23
=> Feature/add recipes to cook/rh

dist/index.html, src/scripts.js, src/styles.css
- Creates functionality for favoriting recipes on the DOM
- Creates functionality for filtering favorite recipes on the DOM
- `scripts.js`
- Filtering favorited recipes
- N/A
- N/A
- N/A
- N/A
Close Issues:
=> Feature/favorite recipes/rh

dist/index.html, src/scripts.js, src/styles.css
- Create HTML for `recipesToCook` section
- Create event listeners for heart button and recipes to cook sections
- Create home button functionality
- Add code to stop duplicate display in favorites and recipes to cook pages
- Add images to `createRecipeList` function
- Add parameters to `displayRecipe` function to improve functionality
- Modify CSS to better accomodate ruberic
- Add eventlisteners for showing and hiding pages
- `scripts.js`
- Recipes to Cook page
- Pantry Page
- Corrected duplicate recipes 
- Heart button color status changes if it has been favorited
- HTML
- CSS
- `scripts.js`
- #43 
Is there anything …
=> Feature/recipes to cook/ow

dist/index.html, src/apiCalls.js, src/scripts.js
- Creates functionality for API imports
- `apiCalls.js`
- API data imported
- Data input for project
- N/A
- N/A
-
Close Issues:
Close #46
=> Feature/fetch data/nb

dist/index.html, src/scripts.js, src/styles.css
- Add additional CSS styling for website look and feel
- 
-
-
-
-
-
Close Issues:
=> Add CSS styling

dist/index.html, src/scripts.js, src/styles.css
- Refactors CSS and completes styling for website look
- styles.css
- 
- CSS file 
- 
-
-
Close Issues:
=> Complete CSS styling

dist/index.html, src/classes/User.js, src/scripts.js, src/styles.css, test/User-test.js
- Add pantry page to HTML
- Add form to pantry page
- Update `User` class with methods:
1) `getPantryInfo`
2) `determineAmountOfIngredients`
- `User.js`
- New pantry page
- New methods for user class
- Add ingredients to `User-test.js` mock data
- N/A
- N/A
- N/A
Close Issues:
Close #63
=> Feature/pantry page/ow

src/apiCalls.js, src/classes/User.js, test/User-test.js
- Adds function to determine missing ingredients from pantry for a recipe
- `User.js`
- functionality to determine missing ingredients
- fetch call to retrieve local data
- N/A
- N/A
- N/A
Close Issues:
=> Feature/user pantry issue/ow

dist/index.html, src/apiCalls.js, src/classes/User.js, src/scripts.js, src/styles.css, test/User-test.js
- Creates user functionality for if a user has enough ingredients to cook a meal and can fill out a form to add ingredients to their pantry
- scripts.js & apiCalls.js
- Pantry viewing ability / error handling for if a user can cook a recipe or not
- 
- 
- 
-
Close Issues:
close #66
=> Feature/pantry user story/rh

src/apiCalls.js, src/scripts.js
- Creates functionality to cook a recipe and have it remove the ingredients from the pantry and updated functionality to post new ingredients to pantry
- `apiCalls.js`
- Add and remove ingredients from pantry
- N/A
- error handling issues (422 unprocessible entity)
- N/A
- refactor order of functions in scripts, remember to reset to randomized user
Close Issues:
Close #70
Close #72 
Close #71 
Close #69
=> Feature/api post issue/nb

dist/index.html, src/apiCalls.js, src/classes/User.js, src/scripts.js, src/styles.css
- Updates the application for error handling
- `apiCalls.js`
- error handling
- removed comments and console logs from scripts and User class
- N/A
- N/A
- N/A
Close Issues:
Close #74 
Close #76
=> Feature/error handling/nb

src/apiCalls.js, src/domUpdates.js, src/scripts.js
- Creates file `domUpdates.js`
- Move functions from `scripts.js` to `domUpdates.js`
- `domUpdates.js`
- New file implementation for `domUpdates`
- `scripts.js`
- N/A
- N/A
-
Close Issues:
Close #60
=> Refactor/dom updates/ow
